#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 15 22:32:23 2024

@author: J.Cabrera-Moreno
Postdoctoral Fellow
Evolutionary Cognition Group
Institute of Evolutionary Anthropology
University of Zürich

Description:
    The following code serves a satelite code for handling
    the creation of a loging file and the loging of the data
    generated by clientPump.py
"""

import os
from datetime import datetime

class FileManager:
    def __init__(self, directory):
        self.directory = directory
        self.ensure_directory_exists()

    def ensure_directory_exists(self):
        if not os.path.exists(self.directory):
            os.makedirs(self.directory)

    def get_current_datetime(self, filename):
        # Get the current date and time
        now = datetime.now()
        
        # Format the date and time in the specified format
        if not filename:
            formatted_datetime = now.strftime('%Y%m%d%H%M%S%f')
        else:
            formatted_datetime = now.strftime('%Y%m%d%H%M%S')
        
        return formatted_datetime

    def create_file(self):
        # Get the current date-time filename
        formatted_datetime = self.get_current_datetime(True)
        
        # Append '.txt' to the formatted date and time
        filename = f"{formatted_datetime}.txt"
        
        # Create the full file path
        file_path = os.path.join(self.directory, filename)
        
        # Create and open the file
        with open(file_path, 'w') as file:
            file.write("date,event\n")
        
        return file_path

    def log_to_file(self, file_path, log):
        # Append a new line to the existing file
        with open(file_path, 'a') as file:
            file.write(log + '\n')

if __name__ == "__main__":
    # Example usage
    directory = '/home/pi/Desktop/DATA'  # Replace with pertinent directory
    file_manager = FileManager(directory)
    
    # Create a new file
    created_file_path = file_manager.create_file()
    print(f"File created: {created_file_path}")
    
    # Append a new line to the created file
    file_manager.log_to_file(created_file_path, "")
    print(f"New line appended to: {created_file_path}")
